---

version: "3.7"

services:
  # ここでimage名を指定する理由
  # webpackサービスで同じimageを使うことが可能になる
  app: &app_base
    working_dir: /app
    command: ./startup.sh
    image: rails6-using-engine_app
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - ~/bundle-install:/app/vendor/bundle
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:3000
    links:
      - postgres
      - chrome
    tty: true
    stdin_open: true

  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    ports:
      - 3035:3035
    depends_on:
      - app
    tty: false
    stdin_open: false

  postgres:
    image: postgres:11.2
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  chrome:
    container_name: chrome
    image: selenium/standalone-chrome
    #image: selenium/standalone-chrome-debug:3.141.59-gold
    ports:
      - 4444:4444
