---

version: "3.7"

services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/app/vendor/bundle

  app:
    working_dir: /app
    command: ./startup.sh
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:3000
    links:
      - postgres

  postgres:
    image: postgres:11.2
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432

volumes:
  bundle_install:
    driver: local
